secreen_capture:
  fps: 5
  region: full
  custom_region:
    left: 0
    top: 0
    width: 1920
    height: 1080
  image_format: RGB
text_recognition:
  engine: tesseract
  languages:
  - chi_sim
  - eng
  confidence_threshold: 0.7
  preprocess:
    resize_factor: 2.0
    binarization: true
    remove_noise: true
content_analysis:
  detect_ui_elements: true
  detect_tables: true
  detect_images: true
  max_content_items: 50
  context_window: 5
privacy:
  mask_sensitive_data: true
  blocked_regions:
  - face
  - id_card
  - license_plate
  - credit_card
  blocked_applications:
  - passwords
  - banking
local_processing_only: true
