"""
工具函数模块
"""
from app.utils.pagination import (
    paginate,
    paginate_with_transform,
    get_pagination_params,
    paginate_list,
    Paginator,
)
from app.utils.cache import (
    generate_cache_key,
    get_cached,
    set_cached,
    delete_cached,
    delete_pattern,
    cache,
    cache_model,
    invalidate_cache,
    invalidate_model_cache,
    CacheManager,
)
from app.utils.validators import (
    validate_email,
    validate_username,
    validate_password,
    validate_password_simple,
    validate_url,
    validate_phone,
    validate_file_extension,
    validate_image_extension,
    validate_content_length,
    sanitize_html,
    validate_date_range,
    validate_slug,
    generate_slug,
    validate_json_structure,
    validate_pagination_params,
    normalize_phone,
    mask_email,
    mask_phone,
    Validator,
)
from app.utils.helpers import (
    generate_uuid,
    generate_short_id,
    generate_random_string,
    hash_string,
    encode_base64,
    decode_base64,
    get_timestamp,
    get_timestamp_ms,
    timestamp_to_datetime,
    datetime_to_timestamp,
    format_datetime,
    parse_datetime,
    get_time_ago,
    truncate_string,
    remove_duplicates,
    chunk_list,
    flatten_list,
    dict_to_query_string,
    merge_dicts,
    safe_get,
    bytes_to_human_readable,
    clamp,
    is_valid_uuid,
    percentage,
    generate_verification_code,
    obfuscate_string,
    Timer,
)
from app.utils.logger import logger


__all__ = [
    # Pagination
    "paginate",
    "paginate_with_transform",
    "get_pagination_params",
    "paginate_list",
    "Paginator",
    
    # Cache
    "generate_cache_key",
    "get_cached",
    "set_cached",
    "delete_cached",
    "delete_pattern",
    "cache",
    "cache_model",
    "invalidate_cache",
    "invalidate_model_cache",
    "CacheManager",
    
    # Validators
    "validate_email",
    "validate_username",
    "validate_password",
    "validate_password_simple",
    "validate_url",
    "validate_phone",
    "validate_file_extension",
    "validate_image_extension",
    "validate_content_length",
    "sanitize_html",
    "validate_date_range",
    "validate_slug",
    "generate_slug",
    "validate_json_structure",
    "validate_pagination_params",
    "normalize_phone",
    "mask_email",
    "mask_phone",
    "Validator",
    
    # Helpers
    "generate_uuid",
    "generate_short_id",
    "generate_random_string",
    "hash_string",
    "encode_base64",
    "decode_base64",
    "get_timestamp",
    "get_timestamp_ms",
    "timestamp_to_datetime",
    "datetime_to_timestamp",
    "format_datetime",
    "parse_datetime",
    "get_time_ago",
    "truncate_string",
    "remove_duplicates",
    "chunk_list",
    "flatten_list",
    "dict_to_query_string",
    "merge_dicts",
    "safe_get",
    "bytes_to_human_readable",
    "clamp",
    "is_valid_uuid",
    "percentage",
    "generate_verification_code",
    "obfuscate_string",
    "Timer",
    
    # Logger
    "logger",
]

