/**
 * 音效资源常量定义
 * @module constants/sounds
 */

import type { SoundConfig, SoundManagerConfig } from '@/types/sound'
import { SoundCategory, SoundPriority, SoundPlayMode } from '@/types/sound'

/**
 * 音效基础路径
 */
export const SOUND_BASE_PATH = '/src/assets/sounds'

/**
 * 音效ID常量
 */
export const SOUND_IDS = {
  // UI交互音效
  UI_CLICK: 'ui_click',
  UI_HOVER: 'ui_hover',
  UI_OPEN: 'ui_open',
  UI_CLOSE: 'ui_close',
  UI_SUCCESS: 'ui_success',
  UI_ERROR: 'ui_error',
  UI_WARNING: 'ui_warning',
  UI_TOGGLE_ON: 'ui_toggle_on',
  UI_TOGGLE_OFF: 'ui_toggle_off',
  UI_SLIDE: 'ui_slide',
  UI_POPUP: 'ui_popup',
  UI_DROPDOWN: 'ui_dropdown',
  
  // 角色动作音效
  CHARACTER_TAP: 'character_tap',
  CHARACTER_DRAG: 'character_drag',
  CHARACTER_IDLE: 'character_idle',
  CHARACTER_HAPPY: 'character_happy',
  CHARACTER_SAD: 'character_sad',
  CHARACTER_SURPRISED: 'character_surprised',
  CHARACTER_THINKING: 'character_thinking',
  CHARACTER_GREETING: 'character_greeting',
  CHARACTER_GOODBYE: 'character_goodbye',
  CHARACTER_YAWN: 'character_yawn',
  CHARACTER_STRETCH: 'character_stretch',
  
  // 对话相关音效
  CHAT_SEND: 'chat_send',
  CHAT_RECEIVE: 'chat_receive',
  CHAT_TYPING: 'chat_typing',
  CHAT_VOICE_START: 'chat_voice_start',
  CHAT_VOICE_END: 'chat_voice_end',
  CHAT_VOICE_ERROR: 'chat_voice_error',
  CHAT_CLEAR: 'chat_clear',
  
  // 系统通知音效
  NOTIFICATION_INFO: 'notification_info',
  NOTIFICATION_SUCCESS: 'notification_success',
  NOTIFICATION_WARNING: 'notification_warning',
  NOTIFICATION_ERROR: 'notification_error',
  NOTIFICATION_MESSAGE: 'notification_message',
  NOTIFICATION_REMINDER: 'notification_reminder',
  
  // 环境音效
  AMBIENT_RAIN: 'ambient_rain',
  AMBIENT_WIND: 'ambient_wind',
  AMBIENT_CAFE: 'ambient_cafe',
  AMBIENT_NATURE: 'ambient_nature',
  AMBIENT_NIGHT: 'ambient_night',
  
  // 背景音乐
  BGM_MAIN: 'bgm_main',
  BGM_RELAXING: 'bgm_relaxing',
  BGM_ENERGETIC: 'bgm_energetic',
  BGM_FOCUS: 'bgm_focus',
} as const

export type SoundId = typeof SOUND_IDS[keyof typeof SOUND_IDS]

/**
 * 音效配置列表
 */
export const SOUND_CONFIGS: SoundConfig[] = [
  // ==================== UI交互音效 ====================
  {
    id: SOUND_IDS.UI_CLICK,
    path: `${SOUND_BASE_PATH}/effects/ui/click.mp3`,
    category: SoundCategory.UI,
    name: '点击音效',
    description: '按钮点击时的音效',
    volume: 0.6,
    priority: SoundPriority.NORMAL,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 50,
  },
  {
    id: SOUND_IDS.UI_HOVER,
    path: `${SOUND_BASE_PATH}/effects/ui/hover.mp3`,
    category: SoundCategory.UI,
    name: '悬停音效',
    description: '鼠标悬停在可交互元素上的音效',
    volume: 0.4,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 30,
  },
  {
    id: SOUND_IDS.UI_OPEN,
    path: `${SOUND_BASE_PATH}/effects/ui/open.mp3`,
    category: SoundCategory.UI,
    name: '打开音效',
    description: '窗口、面板打开的音效',
    volume: 0.7,
    priority: SoundPriority.NORMAL,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 100,
    fadeOutDuration: 100,
  },
  {
    id: SOUND_IDS.UI_CLOSE,
    path: `${SOUND_BASE_PATH}/effects/ui/close.mp3`,
    category: SoundCategory.UI,
    name: '关闭音效',
    description: '窗口、面板关闭的音效',
    volume: 0.7,
    priority: SoundPriority.NORMAL,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 100,
  },
  {
    id: SOUND_IDS.UI_SUCCESS,
    path: `${SOUND_BASE_PATH}/effects/ui/success.mp3`,
    category: SoundCategory.UI,
    name: '成功音效',
    description: '操作成功时的提示音效',
    volume: 0.8,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 200,
  },
  {
    id: SOUND_IDS.UI_ERROR,
    path: `${SOUND_BASE_PATH}/effects/ui/error.mp3`,
    category: SoundCategory.UI,
    name: '错误音效',
    description: '操作失败或错误时的提示音效',
    volume: 0.7,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 200,
  },
  {
    id: SOUND_IDS.UI_WARNING,
    path: `${SOUND_BASE_PATH}/effects/ui/warning.mp3`,
    category: SoundCategory.UI,
    name: '警告音效',
    description: '警告提示的音效',
    volume: 0.7,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 200,
  },
  {
    id: SOUND_IDS.UI_TOGGLE_ON,
    path: `${SOUND_BASE_PATH}/effects/ui/toggle_on.mp3`,
    category: SoundCategory.UI,
    name: '开关打开音效',
    description: '开关按钮打开时的音效',
    volume: 0.5,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 50,
  },
  {
    id: SOUND_IDS.UI_TOGGLE_OFF,
    path: `${SOUND_BASE_PATH}/effects/ui/toggle_off.mp3`,
    category: SoundCategory.UI,
    name: '开关关闭音效',
    description: '开关按钮关闭时的音效',
    volume: 0.5,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 50,
  },
  {
    id: SOUND_IDS.UI_SLIDE,
    path: `${SOUND_BASE_PATH}/effects/ui/slide.mp3`,
    category: SoundCategory.UI,
    name: '滑动音效',
    description: '滑块调节时的音效',
    volume: 0.4,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.ONCE,
    preload: false,
    fadeInDuration: 0,
    fadeOutDuration: 30,
  },
  {
    id: SOUND_IDS.UI_POPUP,
    path: `${SOUND_BASE_PATH}/effects/ui/popup.mp3`,
    category: SoundCategory.UI,
    name: '弹窗音效',
    description: '弹窗出现时的音效',
    volume: 0.6,
    priority: SoundPriority.NORMAL,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 50,
    fadeOutDuration: 100,
  },
  {
    id: SOUND_IDS.UI_DROPDOWN,
    path: `${SOUND_BASE_PATH}/effects/ui/dropdown.mp3`,
    category: SoundCategory.UI,
    name: '下拉菜单音效',
    description: '下拉菜单展开时的音效',
    volume: 0.5,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.ONCE,
    preload: false,
    fadeInDuration: 0,
    fadeOutDuration: 50,
  },

  // ==================== 角色动作音效 ====================
  {
    id: SOUND_IDS.CHARACTER_TAP,
    path: `${SOUND_BASE_PATH}/effects/character/tap.mp3`,
    category: SoundCategory.CHARACTER,
    name: '点击角色音效',
    description: '点击Live2D角色时的音效',
    volume: 0.7,
    priority: SoundPriority.NORMAL,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 100,
  },
  {
    id: SOUND_IDS.CHARACTER_DRAG,
    path: `${SOUND_BASE_PATH}/effects/character/drag.mp3`,
    category: SoundCategory.CHARACTER,
    name: '拖拽角色音效',
    description: '拖拽Live2D角色时的音效',
    volume: 0.5,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 100,
  },
  {
    id: SOUND_IDS.CHARACTER_IDLE,
    path: `${SOUND_BASE_PATH}/effects/character/idle.mp3`,
    category: SoundCategory.CHARACTER,
    name: '角色待机音效',
    description: '角色处于待机状态时的环境音效',
    volume: 0.3,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.LOOP,
    preload: false,
    fadeInDuration: 2000,
    fadeOutDuration: 2000,
  },
  {
    id: SOUND_IDS.CHARACTER_HAPPY,
    path: `${SOUND_BASE_PATH}/effects/character/happy.mp3`,
    category: SoundCategory.CHARACTER,
    name: '角色开心音效',
    description: '角色表现开心时的音效',
    volume: 0.8,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 200,
  },
  {
    id: SOUND_IDS.CHARACTER_SAD,
    path: `${SOUND_BASE_PATH}/effects/character/sad.mp3`,
    category: SoundCategory.CHARACTER,
    name: '角色伤心音效',
    description: '角色表现伤心时的音效',
    volume: 0.6,
    priority: SoundPriority.NORMAL,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 200,
  },
  {
    id: SOUND_IDS.CHARACTER_SURPRISED,
    path: `${SOUND_BASE_PATH}/effects/character/surprised.mp3`,
    category: SoundCategory.CHARACTER,
    name: '角色惊讶音效',
    description: '角色表现惊讶时的音效',
    volume: 0.8,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 150,
  },
  {
    id: SOUND_IDS.CHARACTER_THINKING,
    path: `${SOUND_BASE_PATH}/effects/character/thinking.mp3`,
    category: SoundCategory.CHARACTER,
    name: '角色思考音效',
    description: '角色思考时的音效',
    volume: 0.5,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 100,
    fadeOutDuration: 200,
  },
  {
    id: SOUND_IDS.CHARACTER_GREETING,
    path: `${SOUND_BASE_PATH}/effects/character/greeting.mp3`,
    category: SoundCategory.CHARACTER,
    name: '角色打招呼音效',
    description: '角色打招呼时的音效',
    volume: 0.8,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 200,
  },
  {
    id: SOUND_IDS.CHARACTER_GOODBYE,
    path: `${SOUND_BASE_PATH}/effects/character/goodbye.mp3`,
    category: SoundCategory.CHARACTER,
    name: '角色告别音效',
    description: '角色告别时的音效',
    volume: 0.7,
    priority: SoundPriority.NORMAL,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 200,
  },
  {
    id: SOUND_IDS.CHARACTER_YAWN,
    path: `${SOUND_BASE_PATH}/effects/character/yawn.mp3`,
    category: SoundCategory.CHARACTER,
    name: '角色打哈欠音效',
    description: '角色打哈欠时的音效',
    volume: 0.6,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.ONCE,
    preload: false,
    fadeInDuration: 0,
    fadeOutDuration: 300,
  },
  {
    id: SOUND_IDS.CHARACTER_STRETCH,
    path: `${SOUND_BASE_PATH}/effects/character/stretch.mp3`,
    category: SoundCategory.CHARACTER,
    name: '角色伸懒腰音效',
    description: '角色伸懒腰时的音效',
    volume: 0.6,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.ONCE,
    preload: false,
    fadeInDuration: 0,
    fadeOutDuration: 200,
  },

  // ==================== 对话相关音效 ====================
  {
    id: SOUND_IDS.CHAT_SEND,
    path: `${SOUND_BASE_PATH}/effects/chat/send.mp3`,
    category: SoundCategory.CHAT,
    name: '发送消息音效',
    description: '发送聊天消息时的音效',
    volume: 0.7,
    priority: SoundPriority.NORMAL,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 100,
  },
  {
    id: SOUND_IDS.CHAT_RECEIVE,
    path: `${SOUND_BASE_PATH}/effects/chat/receive.mp3`,
    category: SoundCategory.CHAT,
    name: '接收消息音效',
    description: '收到聊天消息时的音效',
    volume: 0.7,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 100,
  },
  {
    id: SOUND_IDS.CHAT_TYPING,
    path: `${SOUND_BASE_PATH}/effects/chat/typing.mp3`,
    category: SoundCategory.CHAT,
    name: '打字音效',
    description: '对方正在输入时的音效',
    volume: 0.4,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.LOOP,
    preload: true,
    fadeInDuration: 300,
    fadeOutDuration: 300,
  },
  {
    id: SOUND_IDS.CHAT_VOICE_START,
    path: `${SOUND_BASE_PATH}/effects/chat/voice_start.mp3`,
    category: SoundCategory.CHAT,
    name: '开始语音音效',
    description: '开始语音输入时的音效',
    volume: 0.8,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 100,
  },
  {
    id: SOUND_IDS.CHAT_VOICE_END,
    path: `${SOUND_BASE_PATH}/effects/chat/voice_end.mp3`,
    category: SoundCategory.CHAT,
    name: '结束语音音效',
    description: '结束语音输入时的音效',
    volume: 0.7,
    priority: SoundPriority.NORMAL,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 100,
  },
  {
    id: SOUND_IDS.CHAT_VOICE_ERROR,
    path: `${SOUND_BASE_PATH}/effects/chat/voice_error.mp3`,
    category: SoundCategory.CHAT,
    name: '语音错误音效',
    description: '语音输入错误时的音效',
    volume: 0.7,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 150,
  },
  {
    id: SOUND_IDS.CHAT_CLEAR,
    path: `${SOUND_BASE_PATH}/effects/chat/clear.mp3`,
    category: SoundCategory.CHAT,
    name: '清空聊天音效',
    description: '清空聊天记录时的音效',
    volume: 0.6,
    priority: SoundPriority.NORMAL,
    playMode: SoundPlayMode.ONCE,
    preload: false,
    fadeInDuration: 0,
    fadeOutDuration: 100,
  },

  // ==================== 系统通知音效 ====================
  {
    id: SOUND_IDS.NOTIFICATION_INFO,
    path: `${SOUND_BASE_PATH}/effects/notification/info.mp3`,
    category: SoundCategory.NOTIFICATION,
    name: '信息提示音效',
    description: '一般信息通知的音效',
    volume: 0.7,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 200,
  },
  {
    id: SOUND_IDS.NOTIFICATION_SUCCESS,
    path: `${SOUND_BASE_PATH}/effects/notification/success.mp3`,
    category: SoundCategory.NOTIFICATION,
    name: '成功通知音效',
    description: '成功通知的音效',
    volume: 0.8,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 200,
  },
  {
    id: SOUND_IDS.NOTIFICATION_WARNING,
    path: `${SOUND_BASE_PATH}/effects/notification/warning.mp3`,
    category: SoundCategory.NOTIFICATION,
    name: '警告通知音效',
    description: '警告通知的音效',
    volume: 0.8,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 200,
  },
  {
    id: SOUND_IDS.NOTIFICATION_ERROR,
    path: `${SOUND_BASE_PATH}/effects/notification/error.mp3`,
    category: SoundCategory.NOTIFICATION,
    name: '错误通知音效',
    description: '错误通知的音效',
    volume: 0.8,
    priority: SoundPriority.CRITICAL,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 200,
  },
  {
    id: SOUND_IDS.NOTIFICATION_MESSAGE,
    path: `${SOUND_BASE_PATH}/effects/notification/message.mp3`,
    category: SoundCategory.NOTIFICATION,
    name: '新消息通知音效',
    description: '收到新消息的通知音效',
    volume: 0.7,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: true,
    fadeInDuration: 0,
    fadeOutDuration: 150,
  },
  {
    id: SOUND_IDS.NOTIFICATION_REMINDER,
    path: `${SOUND_BASE_PATH}/effects/notification/reminder.mp3`,
    category: SoundCategory.NOTIFICATION,
    name: '提醒通知音效',
    description: '定时提醒的通知音效',
    volume: 0.7,
    priority: SoundPriority.HIGH,
    playMode: SoundPlayMode.ONCE,
    preload: false,
    fadeInDuration: 0,
    fadeOutDuration: 200,
  },

  // ==================== 环境音效 ====================
  {
    id: SOUND_IDS.AMBIENT_RAIN,
    path: `${SOUND_BASE_PATH}/effects/ambient/rain.mp3`,
    category: SoundCategory.AMBIENT,
    name: '雨声环境音',
    description: '下雨的环境音效',
    volume: 0.3,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.LOOP,
    preload: false,
    fadeInDuration: 3000,
    fadeOutDuration: 3000,
  },
  {
    id: SOUND_IDS.AMBIENT_WIND,
    path: `${SOUND_BASE_PATH}/effects/ambient/wind.mp3`,
    category: SoundCategory.AMBIENT,
    name: '风声环境音',
    description: '风吹的环境音效',
    volume: 0.3,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.LOOP,
    preload: false,
    fadeInDuration: 3000,
    fadeOutDuration: 3000,
  },
  {
    id: SOUND_IDS.AMBIENT_CAFE,
    path: `${SOUND_BASE_PATH}/effects/ambient/cafe.mp3`,
    category: SoundCategory.AMBIENT,
    name: '咖啡厅环境音',
    description: '咖啡厅的环境音效',
    volume: 0.4,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.LOOP,
    preload: false,
    fadeInDuration: 3000,
    fadeOutDuration: 3000,
  },
  {
    id: SOUND_IDS.AMBIENT_NATURE,
    path: `${SOUND_BASE_PATH}/effects/ambient/nature.mp3`,
    category: SoundCategory.AMBIENT,
    name: '大自然环境音',
    description: '大自然的环境音效',
    volume: 0.3,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.LOOP,
    preload: false,
    fadeInDuration: 3000,
    fadeOutDuration: 3000,
  },
  {
    id: SOUND_IDS.AMBIENT_NIGHT,
    path: `${SOUND_BASE_PATH}/effects/ambient/night.mp3`,
    category: SoundCategory.AMBIENT,
    name: '夜晚环境音',
    description: '夜晚的环境音效',
    volume: 0.3,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.LOOP,
    preload: false,
    fadeInDuration: 3000,
    fadeOutDuration: 3000,
  },

  // ==================== 背景音乐 ====================
  {
    id: SOUND_IDS.BGM_MAIN,
    path: `${SOUND_BASE_PATH}/bgm/main.mp3`,
    category: SoundCategory.BGM,
    name: '主题背景音乐',
    description: '主界面的背景音乐',
    volume: 0.4,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.LOOP,
    preload: false,
    fadeInDuration: 5000,
    fadeOutDuration: 5000,
  },
  {
    id: SOUND_IDS.BGM_RELAXING,
    path: `${SOUND_BASE_PATH}/bgm/relaxing.mp3`,
    category: SoundCategory.BGM,
    name: '放松背景音乐',
    description: '放松舒缓的背景音乐',
    volume: 0.3,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.LOOP,
    preload: false,
    fadeInDuration: 5000,
    fadeOutDuration: 5000,
  },
  {
    id: SOUND_IDS.BGM_ENERGETIC,
    path: `${SOUND_BASE_PATH}/bgm/energetic.mp3`,
    category: SoundCategory.BGM,
    name: '活力背景音乐',
    description: '充满活力的背景音乐',
    volume: 0.4,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.LOOP,
    preload: false,
    fadeInDuration: 5000,
    fadeOutDuration: 5000,
  },
  {
    id: SOUND_IDS.BGM_FOCUS,
    path: `${SOUND_BASE_PATH}/bgm/focus.mp3`,
    category: SoundCategory.BGM,
    name: '专注背景音乐',
    description: '帮助专注的背景音乐',
    volume: 0.3,
    priority: SoundPriority.LOW,
    playMode: SoundPlayMode.LOOP,
    preload: false,
    fadeInDuration: 5000,
    fadeOutDuration: 5000,
  },
]

/**
 * 默认音效管理器配置
 */
export const DEFAULT_SOUND_MANAGER_CONFIG: SoundManagerConfig = {
  globalVolume: 0.7,
  globalMuted: false,
  maxConcurrent: 10,
  defaultFadeIn: 100,
  defaultFadeOut: 200,
  basePath: SOUND_BASE_PATH,
  debug: import.meta.env.DEV,
  poolSize: 20,
  cacheStrategy: 'preload',
  formatPriority: ['mp3', 'ogg', 'wav'],
}

/**
 * 音效分组配置
 */
export const SOUND_GROUPS = {
  UI: {
    id: 'ui',
    name: 'UI音效',
    sounds: Object.values(SOUND_IDS).filter((id) => id.startsWith('ui_')),
    volume: 1.0,
    muted: false,
  },
  CHARACTER: {
    id: 'character',
    name: '角色音效',
    sounds: Object.values(SOUND_IDS).filter((id) => id.startsWith('character_')),
    volume: 1.0,
    muted: false,
  },
  CHAT: {
    id: 'chat',
    name: '对话音效',
    sounds: Object.values(SOUND_IDS).filter((id) => id.startsWith('chat_')),
    volume: 1.0,
    muted: false,
  },
  NOTIFICATION: {
    id: 'notification',
    name: '通知音效',
    sounds: Object.values(SOUND_IDS).filter((id) => id.startsWith('notification_')),
    volume: 1.0,
    muted: false,
  },
  AMBIENT: {
    id: 'ambient',
    name: '环境音效',
    sounds: Object.values(SOUND_IDS).filter((id) => id.startsWith('ambient_')),
    volume: 1.0,
    muted: false,
  },
  BGM: {
    id: 'bgm',
    name: '背景音乐',
    sounds: Object.values(SOUND_IDS).filter((id) => id.startsWith('bgm_')),
    volume: 1.0,
    muted: false,
  },
} as const

/**
 * 音效预设配置
 */
export const SOUND_PRESETS = {
  QUIET: {
    id: 'quiet',
    name: '安静模式',
    description: '最小化音效，适合安静环境',
    config: {
      globalVolume: 0.3,
      maxConcurrent: 5,
    },
    groups: [
      { ...SOUND_GROUPS.UI, volume: 0.2 },
      { ...SOUND_GROUPS.CHARACTER, volume: 0.3 },
      { ...SOUND_GROUPS.CHAT, volume: 0.3 },
      { ...SOUND_GROUPS.NOTIFICATION, volume: 0.5 },
      { ...SOUND_GROUPS.AMBIENT, muted: true },
      { ...SOUND_GROUPS.BGM, muted: true },
    ],
  },
  NORMAL: {
    id: 'normal',
    name: '标准模式',
    description: '平衡的音效设置',
    config: {
      globalVolume: 0.7,
      maxConcurrent: 10,
    },
    groups: Object.values(SOUND_GROUPS),
  },
  IMMERSIVE: {
    id: 'immersive',
    name: '沉浸模式',
    description: '最大化音效体验',
    config: {
      globalVolume: 1.0,
      maxConcurrent: 15,
    },
    groups: [
      { ...SOUND_GROUPS.UI, volume: 1.0 },
      { ...SOUND_GROUPS.CHARACTER, volume: 1.0 },
      { ...SOUND_GROUPS.CHAT, volume: 1.0 },
      { ...SOUND_GROUPS.NOTIFICATION, volume: 1.0 },
      { ...SOUND_GROUPS.AMBIENT, volume: 0.8 },
      { ...SOUND_GROUPS.BGM, volume: 0.6 },
    ],
  },
  FOCUS: {
    id: 'focus',
    name: '专注模式',
    description: '减少干扰，保留重要通知',
    config: {
      globalVolume: 0.5,
      maxConcurrent: 3,
    },
    groups: [
      { ...SOUND_GROUPS.UI, volume: 0.2, muted: false },
      { ...SOUND_GROUPS.CHARACTER, muted: true },
      { ...SOUND_GROUPS.CHAT, volume: 0.3 },
      { ...SOUND_GROUPS.NOTIFICATION, volume: 0.7 },
      { ...SOUND_GROUPS.AMBIENT, volume: 0.4 },
      { ...SOUND_GROUPS.BGM, volume: 0.3 },
    ],
  },
} as const

/**
 * 获取音效配置
 */
export function getSoundConfig(id: string): SoundConfig | undefined {
  return SOUND_CONFIGS.find((config) => config.id === id)
}

/**
 * 获取分类音效列表
 */
export function getSoundsByCategory(category: SoundCategory): SoundConfig[] {
  return SOUND_CONFIGS.filter((config) => config.category === category)
}

/**
 * 获取需要预加载的音效列表
 */
export function getPreloadSounds(): SoundConfig[] {
  return SOUND_CONFIGS.filter((config) => config.preload)
}

