name: 🐛 Bug 报告
description: 报告一个 bug 来帮助我们改进
title: "[Bug] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感谢你花时间填写这个 bug 报告！
        
        在提交之前，请确保：
        - 你已经搜索了现有的 issues
        - 你使用的是最新版本的应用
        - 这确实是一个 bug，而不是功能请求

  - type: checkboxes
    id: checklist
    attributes:
      label: 提交前检查
      options:
        - label: 我已经搜索了现有的 issues
          required: true
        - label: 我使用的是最新版本
          required: true
        - label: 我已经阅读了文档
          required: true

  - type: input
    id: version
    attributes:
      label: 应用版本
      description: 你使用的应用版本是什么？
      placeholder: "例如：v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 操作系统
      description: 你在哪个操作系统上遇到了这个问题？
      options:
        - Windows 11
        - Windows 10
        - macOS Ventura (13.x)
        - macOS Monterey (12.x)
        - macOS Big Sur (11.x)
        - Ubuntu 22.04
        - Ubuntu 20.04
        - 其他 Linux 发行版
        - 其他
    validations:
      required: true

  - type: input
    id: platform-version
    attributes:
      label: 系统版本
      description: 具体的操作系统版本
      placeholder: "例如：Windows 11 22H2, macOS 13.2.1, Ubuntu 22.04.1"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug 描述
      description: 清晰简洁地描述这个 bug
      placeholder: 描述发生了什么...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期望行为
      description: 清晰简洁地描述你期望发生什么
      placeholder: 描述你期望的行为...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 重现步骤
      description: 详细的重现步骤
      placeholder: |
        1. 打开应用
        2. 点击 '...'
        3. 滚动到 '...'
        4. 看到错误
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: 错误信息
      description: 如果有错误信息，请粘贴在这里
      render: text
      placeholder: 粘贴错误信息...

  - type: textarea
    id: logs
    attributes:
      label: 日志文件
      description: 如果有相关的日志文件，请粘贴在这里
      render: text
      placeholder: 粘贴日志内容...

  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: 如果适用，添加截图来帮助解释你的问题
      placeholder: 拖拽图片到这里或点击上传...

  - type: dropdown
    id: frequency
    attributes:
      label: 问题频率
      description: 这个问题多久发生一次？
      options:
        - 总是发生
        - 经常发生
        - 偶尔发生
        - 很少发生
        - 只发生过一次
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 严重程度
      description: 这个问题对你的使用有多大影响？
      options:
        - 严重 - 应用无法使用
        - 高 - 主要功能受影响
        - 中 - 部分功能受影响
        - 低 - 轻微影响
        - 很低 - 几乎没有影响
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 添加任何其他关于问题的信息
      placeholder: 任何其他相关信息...

  - type: checkboxes
    id: contribution
    attributes:
      label: 贡献意愿
      description: 你是否愿意帮助修复这个问题？
      options:
        - label: 我愿意提交 PR 来修复这个问题
        - label: 我愿意帮助测试修复方案
        - label: 我可以提供更多信息或协助调试