# Dependabot 自动依赖更新配置
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # npm 依赖更新
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    reviewers:
      - "tech-lead"
    assignees:
      - "devops-team"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    # 版本更新策略
    versioning-strategy: increase
    # 允许的更新类型
    allow:
      - dependency-type: "all"
    # 忽略的依赖
    ignore:
      # 主要版本更新需要手动处理
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
    # 分组更新
    groups:
      # TypeScript 相关
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "@types/*"
      # React 生态
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
      # 测试工具
      testing:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "playwright"
          - "@playwright/*"
          - "jsdom"
      # ESLint 和代码格式化
      linting:
        patterns:
          - "eslint"
          - "eslint-*"
          - "prettier"
          - "prettier-*"
      # Tailwind CSS
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "postcss"

  # GitHub Actions 更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    reviewers:
      - "devops-team"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"

  # Docker 依赖更新（如果使用）
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    reviewers:
      - "devops-team"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"

