app_name: Zishu-sense
app_version: 1.0.0
app_description: AI虚拟角色
language: zh-CN
paths:
  data_dir: ./data
  models_dir: ./models
  logs_dir: ./data/logs
  cache_dir: ./cache
default_mode: cli
debug: true
