data_sources:
  anime_dialogue:
    path: ./data/raw/anime_dialogue
    format: json
    enabled: true
  anime_wiki:
    path: ./data/raw/anime_wiki
    format: json
    enabled: false
  bilibili_comments:
    path: ./data/raw/bilibili_comments
    format: json
    enabled: false
  bangumi_mega:
    path: ./data/train/bangumi_mega_06102025
    format: json
    enabled: true
    description: Comprehensive anime knowledge base with 211,944 conversations
preprocessing:
  tokenization:
    truncation: true
    max_length: 4096
  text_cleaning:
    remove_urls: true
    remove_emojis: false
    normalize_spaces: true
    preserve_emoji_emoticons: true
    preserve_japanese_terms: true
  augmentation:
    enabled: true
    methods:
    - back_translation
    - synonym_replacement
dataset_splitting:
  train: 0.8
  validation: 0.1
  test: 0.1
  seed: 42
expert_specific_data:
  anime_culture:
  - anime_analysis
  - character_studies
  - bangumi_mega
  anime_language:
  - anime_dialogue
  - character_quotes
  acg_knowledge:
  - anime_wiki
  - game_guides
  - bangumi_mega
  user_interaction:
  - bilibili_comments
