name: backend-tests

on:
  push:
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with: { components: rustfmt, clippy }
      - name: Build
        run: |
          cd desktop_app/src-tauri
          cargo build --locked
      - name: Lints
        run: |
          cd desktop_app/src-tauri
          cargo fmt --all -- --check
          cargo clippy --all-features -- -D warnings
      - name: Tests
        run: |
          cd desktop_app/src-tauri
          cargo test --all-features -- --nocapture


